pub mod config;
pub mod db;
pub mod discovery;
pub mod entity;
pub mod frontmatter;
pub mod hub_feed;
pub mod logging;
pub mod placements;
pub mod presets;
pub mod profiles;
pub mod provider;
pub mod provider_registry;
pub mod registry;
pub mod remote;

pub use config::{AgentsConfig, AppDirs, ProfilesConfig, SourcesConfig};
pub use db::Database;
pub use presets::{AgentPreset, KNOWN_AGENTS, lookup_preset};
pub use provider::SkillProvider;
pub use provider_registry::ProviderRegistry;
pub use registry::Registry;
